# Stack: mariadb
# .env en Vaultwarden

version: '3.8'
services:
  db:
    image: mariadb:10.6
    user: "1001:1001" # Use "dockercontainers" UID & GID: (into host: `id dockercontainers`)
    # healthcheck:
    #   test: mysqladmin ping -h localhost --password=${DFP_DB_ROOT_PASSWORD:?DFP_DB_ROOT_PASSWORD is not defined}
    #   interval: 10s      # Intervalo más largo entre chequeos
    #   timeout: 5s        # Tiempo máximo para esperar una respuesta
    #   retries: 5         # Menor número de reintentos
    #   start_period: 30s # Periodo antes de iniciar los chequeos
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        # delay: 20s
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s
      resources:
        limits:
          cpus: '2' # Based on VPS cpus: If 8vcpus available, you can set to 4 (half of them)
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 300M
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed # Temporary fix for MariaDB 10.6
      # https://mariadb.com/kb/en/innodb-system-variables/#innodb_log_buffer_size
      # 1GB for innodb
      - --innodb-buffer-pool-size=1073741824
      - --log-bin
      - --log-basename=mariadb
      - --expire-logs-days=15
      # Allow root password change if enabled --skip-grant-tables
      # mysql -u root
      # flush privileges;
      # ALTER USER 'root'@'%'  IDENTIFIED BY 'newpassword';
      # - --skip-grant-tables
    environment:
      MYSQL_ROOT_PASSWORD: ${DFP_DB_ROOT_PASSWORD:?DFP_DB_ROOT_PASSWORD is not defined}
      # MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
    ports:
      - "3306:3306"
    volumes:
      - /root/docker_volume_mariadb:/var/lib/mysql
    networks:
      - default
      - mariadb-net
networks:
  mariadb-net:
    external: true
  default:
    driver: overlay
